# https://goreleaser.com

project_name: terraform-provider-stackguardian

#  env_files:
#    github_token: '{{ .Env.SG_GITHUB_KEY_FILEPATH }}'

#  before:
#    hooks:
#      # This is just an example and not a requirement for provider building/publishing
#      # Is it really required?
#      - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GOPRIVATE="github.com/StackGuardian/terraform-provider-stackguardian"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-trimpath'
      - '-v'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  name_template: "v{{.Version}}"
  github:
    owner: stackguardian
    name: terraform-provider-stackguardian
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append
  skip_upload: false

changelog:
  skip: true
  use: github
