#!/usr/bin/env bash
#
# Insert the "docs are being revamped" banner into every generated resource and
# data-source page.
#
# The banner is temporary, so it is injected here rather than pasted into all 32
# templates: removing it later means deleting one line from the `docs-generate`
# Makefile target, not editing 32 files. The wording lives in scripts/docs-banner.md.
#
# This runs as the last step of `make docs-generate`, after tfplugindocs has
# rewritten docs/. Guides and the provider index are deliberately left alone.
#
# Two things make the insertion point trickier than it looks, and both are why this
# is an awk state machine rather than a sed one-liner:
#
#   1. The first line matching /^# / is INSIDE the YAML frontmatter -- every page
#      starts with "---" then "# generated by https://github.com/hashicorp/...".
#      Anchoring on it would write the banner into the frontmatter and break the page.
#      The anchor is the first /^# / AFTER the closing "---".
#
#   2. /^# / recurs throughout each file as Terraform comments inside fenced code
#      blocks (docs/resources/policy.md has 17 such lines). The insertion must happen
#      once and then stop.

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
BANNER_FILE="$REPO_ROOT/scripts/docs-banner.md"
START_MARKER="<!-- docs-revamp-banner:start -->"
END_MARKER="<!-- docs-revamp-banner:end -->"

[ -f "$BANNER_FILE" ] || { echo "missing banner file: $BANNER_FILE" >&2; exit 1; }

injected=0
skipped=0

for f in "$REPO_ROOT"/docs/resources/*.md "$REPO_ROOT"/docs/data-sources/*.md; do
  [ -e "$f" ] || continue
  rel="${f#"$REPO_ROOT"/}"

  # Idempotent: tfplugindocs rewrites these files on every run, so the marker is
  # normally absent, but running this script standalone must not double-inject.
  if grep -qF "$START_MARKER" "$f"; then
    skipped=$((skipped + 1))
    continue
  fi

  tmp="$f.banner.tmp"
  # The banner is read from its file with getline rather than passed via -v:
  # macOS awk rejects embedded newlines in a -v assignment.
  awk -v bf="$BANNER_FILE" -v start="$START_MARKER" -v end="$END_MARKER" '
    function emit_banner(   line) {
      print start
      while ((getline line < bf) > 0) print line
      close(bf)
      print end
    }
    state==0 && NR==1 && $0=="---" { state=1; print; next }
    state==1 && $0=="---"          { state=2; print; next }
    state==2 && /^# / && !done     { print; print ""; emit_banner(); done=1; next }
                                   { print }
    END { exit(done ? 0 : 1) }
  ' "$f" > "$tmp" || {
    rm -f "$tmp"
    echo "ERROR: no heading found after the frontmatter in $rel -- refusing to write" >&2
    exit 1
  }

  mv "$tmp" "$f"
  injected=$((injected + 1))
done

if [ "$skipped" -gt 0 ]; then
  echo "==> banner: injected into $injected pages, $skipped already had it"
else
  echo "==> banner: injected into $injected pages"
fi
