name: "Provider Release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:

  test-provider:
    name: "Test Provider"
    uses: ./.github/workflows/test.yaml

  release-provider:
    name: "Release Provider"
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v2
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
    with:
      setup-go-version-file: 'go.mod'
    needs: test-provider
