name: "Test API-PRD with TF-Provider"  # for API High-Load with examples on API-PRD

on:
  schedule:
    - cron: '*/10 * 1-10 4 *'
  workflow_dispatch:

jobs:

  api_test:
    name: "Test API-PRD with TF-Provider"
    uses: ./.github/workflows/test-api.yaml
    secrets: inherit
    with:
      gitref: main
      testenv: PRD
